export const SAFE_RESPONSE_OPTIONS = 'SAFE_RESPONSE_OPTIONS';
export const RAW_RESPONSE_KEY = 'RAW_RESPONSE';
export const PAGINATED_KEY = 'PAGINATED';
export const RESPONSE_MESSAGE_KEY = 'RESPONSE_MESSAGE';

export const SUCCESS_CODE_KEY = 'SUCCESS_CODE';
export const CURSOR_PAGINATED_KEY = 'CURSOR_PAGINATED';

export const DEFAULT_ERROR_CODE_MAP: Record<number, string> = {
  400: 'BAD_REQUEST',
  401: 'UNAUTHORIZED',
  403: 'FORBIDDEN',
  404: 'NOT_FOUND',
  409: 'CONFLICT',
  422: 'UNPROCESSABLE_ENTITY',
  429: 'TOO_MANY_REQUESTS',
  500: 'INTERNAL_SERVER_ERROR',
};
